---
extends:
  - tribou
  - plugin:flowtype/recommended

parser: typescript-eslint-parser

rules:
  flowtype/require-valid-file-annotation:
    - error
    - always
  react/prefer-stateless-function:
    - error
    - ignorePureComponents: true

  no-duplicate-imports: 0

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
  import/resolver: webpack

env:
  jest: true
