---
extends:
  - tribou
  - plugin:flowtype/recommended

parser: typescript-eslint-parser

rules:
  flowtype/require-valid-file-annotation:
    - error
    - always
  react/prefer-stateless-function:
    - error
    - ignorePureComponents: true

  no-duplicate-imports: 0
  import/extensions:
    - 'error'
    - 'always'
    - js: 'never'
      jsx: 'never'
      ts: 'never'
      tsx: 'never'

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
  import/resolver: webpack
  import/extensions:
    - js
    - json
    - ts
    - tsx

env:
  jest: true
